server:
   port: 8800
spring:
#  application:
#        name: microservice-config-server
  cloud:
        config:
          server:
              git:
               uri: https://git.oschina.net/zhangdihong/spring-config-demo




#eureka:
#  client:
#    healthcheck:
#    enabled: true
#    service-url:
#         defaultZone: http://test1:8081/eureka
#instance:
#      prefer-ip-address: true
#      nstance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
#